name: brick_breaker
description: "Breakout Flutter game."
publish_to: 'none' # prevents the package from being accidentally published to pub.dev using `flutter pub publish`
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flame: ^1.23.0
  flame_audio: ^2.10.7
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0
  google_fonts: ^6.1.0
  pixelarticons: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/audio/
